package com.davis.bean;

import java.util.Date;

public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.id
     *
     * @mbg.generated Thu Dec 02 09:05:38 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.title
     *
     * @mbg.generated Thu Dec 02 09:05:38 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.content_short
     *
     * @mbg.generated Thu Dec 02 09:05:38 CST 2021
     */
    private String contentShort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.display_time
     *
     * @mbg.generated Thu Dec 02 09:05:38 CST 2021
     */
    private Date displayTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.username
     *
     * @mbg.generated Thu Dec 02 09:05:38 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.content
     *
     * @mbg.generated Thu Dec 02 09:05:38 CST 2021
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.id
     *
     * @return the value of t_blog.id
     *
     * @mbg.generated Thu Dec 02 09:05:38 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.id
     *
     * @param id the value for t_blog.id
     *
     * @mbg.generated Thu Dec 02 09:05:38 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.title
     *
     * @return the value of t_blog.title
     *
     * @mbg.generated Thu Dec 02 09:05:38 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.title
     *
     * @param title the value for t_blog.title
     *
     * @mbg.generated Thu Dec 02 09:05:38 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.content_short
     *
     * @return the value of t_blog.content_short
     *
     * @mbg.generated Thu Dec 02 09:05:38 CST 2021
     */
    public String getContentShort() {
        return contentShort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.content_short
     *
     * @param contentShort the value for t_blog.content_short
     *
     * @mbg.generated Thu Dec 02 09:05:38 CST 2021
     */
    public void setContentShort(String contentShort) {
        this.contentShort = contentShort == null ? null : contentShort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.display_time
     *
     * @return the value of t_blog.display_time
     *
     * @mbg.generated Thu Dec 02 09:05:38 CST 2021
     */
    public Date getDisplayTime() {
        return displayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.display_time
     *
     * @param displayTime the value for t_blog.display_time
     *
     * @mbg.generated Thu Dec 02 09:05:38 CST 2021
     */
    public void setDisplayTime(Date displayTime) {
        this.displayTime = displayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.username
     *
     * @return the value of t_blog.username
     *
     * @mbg.generated Thu Dec 02 09:05:38 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.username
     *
     * @param username the value for t_blog.username
     *
     * @mbg.generated Thu Dec 02 09:05:38 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.content
     *
     * @return the value of t_blog.content
     *
     * @mbg.generated Thu Dec 02 09:05:38 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.content
     *
     * @param content the value for t_blog.content
     *
     * @mbg.generated Thu Dec 02 09:05:38 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}